# Generated by Django 5.1.7 on 2025-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_offerdetail_features_offerdetail_offer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=1),
        ),
    ]
