# Generated by Django 5.1.7 on 2025-03-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0004_alter_offer_created_at_alter_offer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offer_pics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
