# Generated by Django 5.1.7 on 2025-03-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0006_alter_offer_image_alter_offerdetail_offer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
