# Generated by Django 5.1.7 on 2025-03-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0007_delete_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer Media'},
        ),
    ]
