# Generated by Django 5.1.7 on 2025-03-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0010_rename_image_offer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='file',
            new_name='image',
        ),
    ]
