# Generated by Django 5.1.7 on 2025-03-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0011_rename_file_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='offer_pics/'),
        ),
    ]
