# Generated by Django 5.1.7 on 2025-03-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_offer_offerdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferDetail',
        ),
    ]
