# Generated by Django 5.1.7 on 2025-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_remove_offerdetail_offer_delete_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='profile_pics/'),
        ),
    ]
