# Generated by Django 5.1.7 on 2025-03-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_delete_fileupload_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
