# Generated by Django 5.1.7 on 2025-03-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.FileField(null=True, upload_to='offer_pics/'),
        ),
    ]
