# Generated by Django 5.1.7 on 2025-03-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
